feature: use kafka to process banner update asynchronously
mash-up-kr/MOIT-backend pull request #98
Opened 2023-07-25 16:50 UTC by SeongYunKim

- 배너 업데이트를 Kafka 메세지 기반 비동기로 처리하도록 수정
- 기존에 FineCreateEvent 를 [여기](https://github.com/mash-up-kr/MOIT-backend/pull/93#discussion_r1271474309) 에서 논의한 것과 같이 FineCreateRequestEvent 로 수정
- KafkaListener 에 컨슈머 그룹 지정

2023-07-26 11:52 UTC, xonmin approved these changes
LGTM 수고하셨습니다 💯

2023-07-26 11:56 UTC, KimDoubleB requested changes

2023-07-26 11:56 UTC, KimDoubleB commented on moit-api/src/main/kotlin/com/mashup/moit/infra/event/kafka/KafkaConsumer.kt
> +            eventProducer.produce(FineCreateEvent(fineId = it.id))
`FINE_CREATE_REQUEST`, `FINE_CREATE`로 둔 이유가 이전에 이야기한 것처럼 구성한 것이죠?
- FINE_CREATE_REQUEST: 벌금 생성 요청 이벤트
- FINE_CREATE: 벌금이 생성됬어 이벤트 -> 벌금 생성에 따라 수행해야 하는 로직

ㅋㅋ 생각보다 보기 어렵군요, 저는 그때 1번 혹은 2번 중 하나만 따르자는 이야긴 줄 알아쓰요

2023-07-26 11:56 UTC, KimDoubleB commented on moit-api/src/main/kotlin/com/mashup/moit/infra/event/MoitEventTopic.kt
> +    const val FINE_CREATE_REQUEST = "fine_create_request"
Request Topic은 다른 object(ex. `KafkaEventRequestTopic`)로 두는 건 어떨까요?
약간 헷갈려서 ㅎㅎㅎㅎ

2023-07-26 12:01 UTC, xonmin commented on moit-api/src/main/kotlin/com/mashup/moit/infra/event/MoitEventTopic.kt
> +    const val FINE_APPROVE = "fine_approve"
참고 ) 
`package org.apache.kafka.clients.admin` 의 `NewTopic` 클래스 이용해서 KafkaConfig 에서 자동 생성할 수있습니다. 
```kotlin
   fun topicWithName(tableName: String): NewTopic {
        return TopicBuilder
            .name(tableName)
            .partitions(partitions)
            .replicas(replicas)
            .config(TopicConfig.RETENTION_MS_CONFIG, getRetention().toLong().toString())
            .config(TopicConfig.SEGMENT_MS_CONFIG, getSegmentMs().toLong().toString())
            .build()
    }
```
ref : https://medium.com/@TimvanBaarsen/programmatically-create-kafka-topics-using-spring-kafka-8db5925ed2b1

2023-07-27 01:46 UTC, KimDoubleB commented on moit-api/src/main/kotlin/com/mashup/moit/infra/event/kafka/KafkaConsumer.kt
> +            eventProducer.produce(FineCreateEvent(fineId = it.id))
오 저는 좋습니다 👍🏻

2023-07-27 14:51 UTC, SeongYunKim commented on moit-api/src/main/kotlin/com/mashup/moit/infra/event/MoitEventTopic.kt
> +    const val FINE_APPROVE = "fine_approve"
오 Configuration 으로도 만들 수 있군요..ㅎㅎ 몰랐습니다!
우선은 upstash 콘솔에서 토픽 만들었습니다~

2023-07-28 02:19 UTC, merged